version: "2"

linters:
  default: none
  enable:
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    goconst: { min-len: 2, min-occurrences: 2 }
    gocyclo: { min-complexity: 20 }
    lll: { line-length: 140 }
    misspell: { locale: US }
    gocritic:
      disabled-checks: [ wrapperFunc, hugeParam ]
      enabled-tags: [ performance, style, experimental ]

  exclusions:
    generated: lax
    rules:
      - { linters: [ gosec ], text: "should have a package comment, unless it's in another file for this package" }
      - { linters: [ gosec ], text: "G505: Blocklisted import crypto/sha1: weak cryptographic primitive" }
      - { linters: [ gosec ], text: "Use of weak cryptographic primitive" }
      - linters: [ gosec ]
        path: _test\.go
        text: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server
      - linters: [ gosec ]
        path: _test\.go
        text: Deferring unsafe method "Close" on type "io.ReadCloser"
      - linters: [ gosec ]
        path: fblog
        text: Errors unhandled
      - linters: [ gosec ]
        path: fblog
        text: Use of unsafe calls should be audited
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
